version: "3.0"
services:
  web:
    container_name: rackspace-basket
    build: .
    ports:
    - "8080:8080"
    env_file: .env-docker
    volumes:
    - ./host_folder/:/apps
    depends_on:
    - mongodb
    links:
    - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
    - basket_mongodb_volume:/data/db/
    ports:
    - "27017:27017"
volumes:
  basket_mongodb_volume:

